parameters:
  - name: stageName
    type: string
    default: none
  - name: stageDisplayname
    type: string
    default: none
  # - name: runStage
  #   type: boolean
  #   default: true
  - name: BaseImageName
    type: string
    default: none
  - name: vmImage
    type: string
    default: windows-2019
  - name: jobcondition
    type: string
    default: ''
  - name: jobDemand
    type: string
    default: ''
  - name: globExpressions
    type: string
    default: ''
  - name: dependsOn
    default: []

stages:
  - stage: ${{ parameters.stageName }}
    condition: ${{ parameters.jobCondition }}

    dependsOn:
      - ${{ parameters.dependsOn }}
      - Init

    displayName: ${{ parameters.stageDisplayname }}
    jobs:
    - job: ${{ parameters.stageName }}
      timeoutInMinutes: 0
      cancelTimeoutInMinutes: 1
      displayName: ${{ parameters.stageDisplayname }}

      variables:
        TemplateS3Namespace: '/image-cd-pipeline'

      pool:
        name: $(agentVMImage)

      steps:
      - template: AWSInitRepos.yml
        parameters:
            gitRepoWriteAccess: false


      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Copy ami to Us-east-1'
        name: Copy
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/CopyAMIToUS.ps1'
          arguments: -BaseImageName '${{ parameters.BaseImageName }}'

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Add Name Tag'
        condition: and(succeeded(), eq(variables['Copy.Exists'], 'True'))
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'us-east-1'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/AddNameTag.ps1'
          arguments:
            -BaseImageName '${{ parameters.BaseImageName }}'
            -Copyid '$(Copy.id)'
            -Copyname '$(Copy.name)'

      - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
        displayName: 'S3 Upload AMI File'
        condition: and(succeeded(), eq(variables['Copy.Exists'], 'True'))
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          bucketName: lansa
          sourceFolder: '$(Pipeline.Workspace)'
          globExpressions: '${{ parameters.globExpressions }}'
          targetFolder: 'templates/$(s3amiUpload)'
          filesAcl: 'public-read'

