parameters:
  - name: deploymentType
    type: string
    default: StackType
    values:
      - StackType
      - Master
      - Preview
      - Production
  - name: stageName
    type: string
    default: none
  - name: stageDisplayname
    type: string
    default: none
  - name: dependsOn
    default: []
  - name: jobName
    type: string
    default: none
  - name: jobDisplayname
    type: string
    default: none
  - name: resourceGroup
    type: string
    default: none
  - name: msiURL
    type: string
    default: none
  - name: stackName
    type: string
    default: none
  - name: certificateBase64Encoded
    type: string
    default: none
  - name: certificatePassword
    type: string
    default: none
  - name: databaseLogin
    type: string
    default: none
  - name: databaseLoginPassword
    type: string
    default: none
  - name: adminUsername
    type: string
    default: none
  - name: adminPassword
    type: string
    default: none
  - name: webUsername
    type: string
    default: none
  - name: webPassword
    type: string
    default: none
  - name: gitBranch
    type: string
    default: none
  - name: vmImage
    type: string
    default: Default
  - name: baseImageName
    type: string
    default: none
  - name: TemplateUrl
    type: string
    default: none
  - name: AwsRegion
    type: string
    default: ap-southeast-2
  - name: s3Region
    type: string
    default: ap-southeast-2
  - name: paramCreateVPC
    type: string
    default: 'No'
  - name: paramCurrentVPC
    type: string
    default: none
  - name: paramAvailabilityZones
    type: string
    default: none
  - name: paramNumberOfAZs
    type: string
    default: none
  - name: paramDBSubnetGroupName
    type: string
    default: none
  - name: paramELBSubnetIds
    type: string
    default: none
  - name: paramStackType
    type: string
    default: Small
  - name: paramLansaMSIKey
    type: string
    default: none
  - name: param10LansaGitRepoBranch
    type: string
    default: none
  - name: paramDBCCSID
    type: string
    default: ''
  - name: paramS3ObjectKey
    type: string
    default: none
  - name: paramTagValue
    type: string
    default: Lansa-Prod
  - name: paramUpdateManagementScripts
    type: string
    default: 'Yes'
  - name: CookbooksBranch
    type: string
    default: none

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn:
      - Init
      - ${{ if ne(parameters.dependsOn, '') }}:
        - ${{ parameters.dependsOn }}

    displayName: ${{ parameters.stageDisplayname }}

    variables:
      - ${{ if endsWith(lower(parameters.BaseImageName), 'j') }}:
        - name: japan_override
          value: '-Language $(jpnLanguage)'
        - name: isJapanese
          value: True
        - name: isImageType
          value: JPN
        - template: vars.yml
          parameters:
            isImageType: JPN
      - ${{ else }}:
        - name: japan_override
          value: ''
        - name: isJapanese
          value: False
        - name: isImageType
          value: ENG
        - template: vars.yml
          parameters:
            isImageType: ENG

    jobs:
      - job: ${{ parameters.jobName }}
        displayName: ${{ parameters.jobDisplayname }}
        timeoutInMinutes: 0
        pool:
          name: ${{ parameters.vmImage }}

        variables:
          - name: StackName
            value: ${{ parameters.stackName }}

        steps:
          - powershell: |
              # Set scriptRepoPath and templateSourceType variables for use in later tasks in this job. This is required as including the expressions inline is not supported by Azure DevOps tasks.

              $repoPath = if ('${{ parameters.deploymentType }}' -eq 'Production' -or '${{ parameters.deploymentType }}' -eq 'Preview') { '_lansa_aws-templates-mp' } else { '_lansa_aws-templates' }
              Write-Host "##vso[task.setvariable variable=scriptRepoPath]$repoPath"

              $templateSource = if ('${{ parameters.deploymentType }}' -eq 'Production' -or '${{ parameters.deploymentType }}' -eq 'Preview') { 'url' } else { 's3' }
              Write-Host "##vso[task.setvariable variable=templateSourceType]$templateSource"

              $StackName = '${{ parameters.stageName }}' -replace "_", "-"
              Write-Host "##vso[task.setvariable variable=StackName]$StackName"

            displayName: 'Set scriptRepoPath and templateSourceType and StackName variables'

          - template: AWSInitRepos.yml
            parameters:
              gitRepoWriteAccess: false
              checkoutTemplateMPRepo: ${{ or(eq(parameters.deploymentType, 'Production'), eq(parameters.deploymentType, 'Preview')) }}

          # - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
          #   name: Gate
          #   displayName: 'Artifact Check: Set Gate Variable'
          #   inputs:
          #     awsCredentials: AzureDevOps
          #     regionName: ${{ parameters.AwsRegion }}
          #     arguments: '-BaseImageName ''${{parameters.baseImageName}}'' -stackname ''${{parameters.stackName}}'''
          #     filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/SetGateVariable.ps1'

          # - powershell: |
          #     Write-Host "Gate.IsEnabled: $(Gate.IsEnabled); Gate.ImageID: $(Gate.ImageID); Gate.version:$(Gate.version); Gate.stack:$(Gate.stack)" | Out-Default
          #   displayName: 'Artifact Check: Output Gate Variable'
          #   condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

          - task: AmazonWebServices.aws-vsts-tools.S3Download.S3Download@1
            displayName: 'S3 Download: TemplateUrl.txt'
            condition: and(succeeded(), or(eq('${{ parameters.deploymentType }}', 'Production'), eq('${{ parameters.deploymentType }}', 'Preview')))
            inputs:
              awsCredentials: AzureDevOps
              regionName: ${{ parameters.s3Region }}
              bucketName: lansa
              sourceFolder: templates/support/scalable/marketplace
              globExpressions: TemplateUrl.txt
              targetFolder: '$(System.DefaultWorkingDirectory)'


          - powershell: |
              Get-ChildItem -Path $(System.DefaultWorkingDirectory)/templates/support/scalable/marketplace
              $path = "$(System.DefaultWorkingDirectory)/templates/support/scalable/marketplace/TemplateUrl.txt"
              if (Test-Path $path) {
                  $url = Get-Content -Path $path
                  Write-Host "##vso[task.setvariable variable=TemplateUrl;isOutput=true]$url"
              } else {
                  Write-Host "path does NOT exist - $path"
              }
            displayName: 'Set TemplateUrl task variable'
            name: Task
            condition: and(succeeded(), or(eq('${{ parameters.deploymentType }}', 'Production'), eq('${{ parameters.deploymentType }}', 'Preview')))

          - powershell: |
              Write-Host "TemplateUrl variable value is - $(Task.TemplateUrl)"
            displayName: 'Output TemplateUrl Variable value'
            condition: and(succeeded(), or(eq('${{ parameters.deploymentType }}', 'Production'), eq('${{ parameters.deploymentType }}', 'Preview')))

          - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
            displayName: 'Cleanup CFN Template: Small Stack-Template'
            inputs:
              awsCredentials: AzureDevOps
              regionName: ${{ parameters.AwsRegion }}
              filePath: '$(Pipeline.Workspace)/$(scriptRepoPath)/scripts/DeletePreviousFailedStack.ps1'
              arguments: '-Gatestack $(StackName)'

          - task: PowerShell@2
            displayName: 'Set CloudFormation Parameter Variables'
            inputs:
              targetType: inline
              script: |
                $deploymentType = "${{ parameters.deploymentType }}"
                if ($deploymentType -eq 'Production') {
                  $lansaGitRepoBranch = '$(CookbooksBranchProduction)'
                } elseif ($deploymentType -eq 'Preview') {
                  $lansaGitRepoBranch = '$(CookbooksBranchPreview)'
                } else {
                  $lansaGitRepoBranch = '${{ parameters.param10LansaGitRepoBranch }}'
                }
                Write-Host "##vso[task.setvariable variable=LansaGitRepoBranch]$lansaGitRepoBranch"

                if ('${{ parameters.paramCurrentVPC }}' -eq 'none') {
                  $currentVPC = '$(CurrentVPC)'
                } else {
                  $currentVPC = '${{ parameters.paramCurrentVPC }}'
                }
                Write-Host "##vso[task.setvariable variable=CurrentVPC]$currentVPC"

                if ('${{ parameters.paramAvailabilityZones }}' -eq 'none') {
                  $availabilityZones = '$(AvailabilityZones)'
                } else {
                  $availabilityZones = '${{ parameters.paramAvailabilityZones }}'
                }
                Write-Host "##vso[task.setvariable variable=AvailabilityZones]$availabilityZones"

                if ('${{ parameters.paramNumberOfAZs }}' -eq 'none') {
                  $numberOfAZs = '$(NumberOfAZs)'
                } else {
                  $numberOfAZs = '${{ parameters.paramNumberOfAZs }}'
                }
                Write-Host "##vso[task.setvariable variable=NumberOfAZs]$numberOfAZs"

                if ('${{ parameters.paramDBSubnetGroupName }}' -eq 'none') {
                  $DBSubnetGroupName = '$(DBSubnetGroupName)'
                } else {
                  $DBSubnetGroupName = '${{ parameters.paramDBSubnetGroupName }}'
                }
                Write-Host "##vso[task.setvariable variable=DBSubnetGroupName]$DBSubnetGroupName"

                if ('${{ parameters.paramELBSubnetIds }}' -eq 'none') {
                  $elbSubnetIds = '$(ELBSubnetIds)'
                } else {
                  $elbSubnetIds = '${{ parameters.paramELBSubnetIds }}'
                }
                Write-Host "##vso[task.setvariable variable=ELBSubnetIds]$elbSubnetIds"

                $templateParams = @(
                    @{
                        ParameterKey = "10LansaGitRepoBranch"
                        ParameterValue = "$LansaGitRepoBranch"
                    },
                    @{
                        ParameterKey = "ImageId"
                        ParameterValue = "$(ImageId)"
                    },
                    @{
                        ParameterKey = "MPS3BucketRegion"
                        ParameterValue = "${{ parameters.AwsRegion }}"
                    },
                    @{
                        ParameterKey = "MPS3KeyPrefix"
                        ParameterValue = "templates/$LansaGitRepoBranch/"
                    },
                    @{
                        ParameterKey = "$(DBPasswordKey)"
                        ParameterValue = "$(DBPasswordValue)"
                    },
                    @{
                        ParameterKey = "$(WebPasswordKey)"
                        ParameterValue = "$(WebPasswordValue)"
                    },
                    @{
                        ParameterKey = "$(KeyNameKey)"
                        ParameterValue = "$(KeyNameValue)"
                    },
                    @{
                        ParameterKey = "$(RemoteAccessLocationKey)"
                        ParameterValue = "$(RemoteAccessLocationValue)"
                    },
                    @{
                        ParameterKey = "$(LansaMSIKey)"
                        ParameterValue = "${{ parameters.paramLansaMSIKey }}"
                    },
                    @{
                        ParameterKey = "CreateVPC"
                        ParameterValue = "${{ parameters.paramCreateVPC }}"
                    },
                    @{
                        ParameterKey = "CurrentVPC"
                        ParameterValue = "$CurrentVPC"
                    },
                    @{
                        ParameterKey = "AvailabilityZones"
                        ParameterValue = "$AvailabilityZones"
                    },
                    @{
                        ParameterKey = "NumberOfAZs"
                        ParameterValue = "$NumberOfAZs"
                    },
                    @{
                        ParameterKey = "DBSubnetGroupName"
                        ParameterValue = "$DBSubnetGroupName"
                    },
                    @{
                        ParameterKey = "ELBSubnetIds"
                        ParameterValue = "$ELBSubnetIds"
                    },
                    @{
                        ParameterKey = "03DBUsername"
                        ParameterValue = "$(03DBUsername)"
                    },
                    @{
                        ParameterKey = "DBCCSID"
                        ParameterValue = "${{ parameters.paramDBCCSID }}"
                    },
                    @{
                        ParameterKey = "TagValue"
                        ParameterValue = "${{ parameters.paramTagValue }}"
                    },
                    @{
                        ParameterKey = "UpdateManagementScripts"
                        ParameterValue = "${{ parameters.paramUpdateManagementScripts }}"
                    }
                )

                if ($deploymentType -ne 'Master') {
                    $templateParams = @(
                        @{
                            ParameterKey = "StackType"
                            ParameterValue = "${{ parameters.paramStackType }}"
                        }
                    ) + $templateParams
                }

                $templateParamsJson = $templateParams | ConvertTo-Json -Compress
                Write-Host "##vso[task.setvariable variable=TemplateParameters]$templateParamsJson"

          - task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
            displayName: 'CFN Template deployment: Small Stack-TemplateTest'
            inputs:
              awsCredentials: AzureDevOps
              regionName: ${{ parameters.AwsRegion }}
              stackName: '$(StackName)'
              templateSource: $(templateSourceType)
              templateUrl: '$(Task.TemplateUrl)'
              s3BucketName: '$(BucketNamePreview)'
              s3ObjectKey: '$(FolderNamePreview)/${{ parameters.paramS3ObjectKey }}'
              templateParametersSource: inline
              templateParameters: $(TemplateParameters)
              tags: 'usage=temp-test'
              onFailure: 'DO_NOTHING'
              timeoutInMins: 100

          - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
            displayName: 'Test CFN Deployment: URL Tests'
            inputs:
              awsCredentials: AzureDevOps
              regionName: ${{ parameters.AwsRegion }}
              filePath: '$(Pipeline.Workspace)/$(scriptRepoPath)/scripts/TestCFNDeployment.ps1'
              arguments:
                -GateStack $(StackName)
                -DisableIntegratorTest
                $japan_override

          - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
            displayName: 'AWS PowerShell: Test Image Version'
            inputs:
              awsCredentials: AzureDevOps
              regionName: ${{ parameters.AwsRegion }}
              filePath: '$(Pipeline.Workspace)/$(scriptRepoPath)/scripts/AlternateImageVersion.ps1'
              arguments:
                -Gatestack '$(StackName)'
                -Gateversion '$(version)'

          - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
            displayName: 'Cleanup CFN Template: Small Stack-Template'
            inputs:
              awsCredentials: AzureDevOps
              regionName: ${{ parameters.AwsRegion }}
              filePath: '$(Pipeline.Workspace)/$(scriptRepoPath)/scripts/DeletePreviousFailedStack.ps1'
              arguments:
                -Gatestack '$(StackName)'
              ignoreLASTEXITCODE: true
            continueOnError: true
