# AWS Test Image
# Defaults to Australian region (ap-southeast-2)
# Can be overridden to US region (us-east-1) by setting the region parameter
# The region parameter is used to determine the VPC and Subnet settings
parameters:
  - name: region
    type: string
    default: ap-southeast-2
  - name: stageName
    type: string
    default: none
  - name: stageDisplayname
    type: string
    default: none
  - name: BaseImageName
    type: string
    default: none
  - name: stackname
    type: string
    default: none
  - name: vmImage
    type: string
    default: default
  - name: jobcondition
    type: string
    default: ''
  - name: jobDemand
    type: string
    default: ''
  - name: dependsOn # Note that only a single dependency is supported here.
    type: string
    default: ''
  - name: paramLansaVersion
    type: string
    default: none
  - name: parammsiURL
    type: string
    default: none
  - name: paramWebserverOSVersionValue
    type: string
    default: none
  - name: paramTagValue
    type: string
    default: none
  - name: paramDBCCSID
    type: string
    default: ''

stages:
  - stage: ${{ parameters.stageName }}
    variables:
      - template: vars.yml

    dependsOn:
      - Init
      - ${{ if ne(parameters.dependsOn, '') }}:
        - ${{ parameters.dependsOn }}

    displayName: ${{ parameters.stageDisplayname }}

    jobs:
    - job: ${{ parameters.stageName }}
      displayName: ${{ parameters.stageDisplayname }}
      condition: ${{ parameters.jobcondition }}
      timeoutInMinutes: 0
      cancelTimeoutInMinutes: 1


      variables:
        - name: TemplateS3Namespace
          value: '/image-cd-pipeline'

        - ${{ if endsWith(lower(parameters.BaseImageName), 'j') }}:
          - name: japan_override
            value: '-Language $(jpnLanguage)'
        - ${{ else }}:
          - name: japan_override
            value: ''

        # Override network settings when in US region to those values declared in the variable group "VPC us-east-1"
        # Otherwise use the default values from the variable group "VPC ap-southeast-2"
        - ${{ if eq(parameters.region, 'us-east-1') }}:
          - name: CurrentVPC
            value: $(CurrentVPCUS)
        - ${{ if eq(parameters.region, 'us-east-1') }}:
          - name: AvailabilityZones
            value: $(AvailabilityZonesUS)
        - ${{ if eq(parameters.region, 'us-east-1') }}:
          - name: NumberOfAZs
            value: $(NumberOfAZsUS)
        - ${{ if eq(parameters.region, 'us-east-1') }}:
          - name: DBSubnetGroupName
            value: $(DBSubnetGroupNameUS)
        - ${{ if eq(parameters.region, 'us-east-1') }}:
          - name: ELBSubnetIds
            value: $(ELBSubnetIdsUS)

      pool:
        name: $(agentVMImage)

      steps:
      - template: AWSInitRepos.yml
        parameters:
            gitRepoWriteAccess: false

      # US-Only Task
      - task: AmazonWebServices.aws-vsts-tools.S3Download.S3Download@1
        displayName: 'S3 Download: lansa'
        condition: and(succeeded(), eq( '${{ parameters.region }}', 'us-east-1' ))
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          bucketName: lansa
          sourceFolder: 'templates/$(s3amiUpload)'
          targetFolder: '$(Pipeline.Workspace)'

      # US-Only Task
      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Overwrite ap-southeast-2 AMI Ids with us-east-1 AMI Ids'
        condition: and(succeeded(), eq( '${{ parameters.region }}', 'us-east-1' ))
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/OverwriteAMIArtifact.ps1'

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Set Gate Variable'
        name: Gate
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          scriptType: 'filePath'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/SetGateVariable.ps1'
          arguments:
            -BaseImageName '${{ parameters.BaseImageName }}'
            -stackname '${{ parameters.stackname }}'

      - task: PowerShell@2
        displayName: 'Output Gate Variables'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        inputs:
          targetType: inline
          script: |
            # Print the Gate variables.
            Write-Host "Gate.IsEnabled: $(Gate.IsEnabled); Gate.ImageID: $(Gate.ImageID); Gate.version:$(Gate.version); Gate.stack:$(Gate.stack)"

      - task: PowerShell@2
        displayName: 'Gate Variables Not Set'
        condition: and(succeeded(), ne(variables['Gate.IsEnabled'], 'True'))
        inputs:
          targetType: inline
          script: |
            Write-Host "Gate variables not set"

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Delete previous Failed Stack'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          arguments: '-Gatestack $(Gate.stack)'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/DeletePreviousFailedStack.ps1'

      - task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
        displayName: 'Deploy AWS template'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          stackName: '$(Gate.stack)'
          templateSource: s3
          s3BucketName: lansa
          s3ObjectKey: 'templates/$(CookbooksBranch)$(TemplateS3Namespace)/lansa-master-win.cfn.template'
          templateParametersSource: inline
          templateParameters: |
            [{
                "ParameterKey": "$(DBPasswordKey)",
                "ParameterValue": "$(DBPasswordValue)"
            }, {
                "ParameterKey": "$(WebPasswordKey)",
                "ParameterValue": "$(WebPasswordValue)"
            }, {
                "ParameterKey": "$(KeyNameKey)",
                "ParameterValue": "$(KeyNameValue)"
            }, {
                "ParameterKey": "$(RemoteAccessLocationKey)",
                "ParameterValue": "$(RemoteAccessLocationValue)"
            }, {
                "ParameterKey": "ImageId",
                "ParameterValue": "$(Gate.ImageID)"
            }, {
                "ParameterKey": "MPS3KeyPrefix",
                "ParameterValue": "templates/$(CookbooksBranch)$(TemplateS3Namespace)/"
            }, {
                "ParameterKey": "TagValue",
                "ParameterValue": "${{ parameters.paramTagValue }}"
            }, {
                "ParameterKey": "10LansaGitRepoBranch",
                "ParameterValue": "$(CookbooksBranch)"
            }, {
                "ParameterKey": "$(LansaMSIKey)",
                "ParameterValue": "${{ parameters.parammsiURL }}"
            }, {
                "ParameterKey": "CurrentVPC",
                "ParameterValue": "$(CurrentVPC)"
            }, {
                "ParameterKey": "AvailabilityZones",
                "ParameterValue": "$(AvailabilityZones)"
            }, {
                "ParameterKey": "NumberOfAZs",
                "ParameterValue": "$(NumberOfAZs)"
            }, {
                "ParameterKey": "DBSubnetGroupName",
                "ParameterValue": "$(DBSubnetGroupName)"
            }, {
                "ParameterKey": "ELBSubnetIds",
                "ParameterValue": "$(ELBSubnetIds)"
            }, {
                "ParameterKey": "DBCCSID",
                "ParameterValue": "${{ parameters.paramDBCCSID }}"
            }, {
                "ParameterKey": "03DBUsername",
                "ParameterValue": "$(03DBUsername)"
            } ]
          tags: 'usage=test-temp'
          onFailure: 'DO_NOTHING'
          disableRollback: true
          warnWhenNoWorkNeeded: false
          outputVariable: deploymentOutput
          captureStackOutputs: asJSON
          captureAsSecuredVars: false
          timeoutInMins: 120

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Print Deployment Output'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          arguments: '-Gatestack $(Gate.stack)'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/PrintDeploymentOutput.ps1'

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Test CFN Deployment: URL tests'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/TestCFNDeployment.ps1'
          arguments:
            -Gatestack $(Gate.stack)
            $(japan_override)
            -DisableIntegratorTest

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Alternate Image Version Test'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'

          arguments:
            -Gatestack '$(Gate.stack)'
            -Gateversion '$(Gate.version)'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/AlternateImageVersion.ps1'

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Delete Stack'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        continueOnError: true
        inputs:
          awsCredentials: AzureDevOps
          regionName: '${{ parameters.region }}'
          arguments: '-Gatestack $(Gate.stack)'
          filePath: '$(Pipeline.Workspace)/_lansa_aws-templates/scripts/DeletePreviousFailedStack.ps1'
          ignoreLASTEXITCODE: true
