parameters:
  - name: OSVersion
    type: string
  - name: LansaMajorVersion
    type: number
  - name: LansaMinorVersion
    type: number
  - name: CloudImageName
    type: string
  - name: ScriptTimeout # Can't refer to a variable in a template thats declared in the parent yml. Hence it must be passed as a parameter
    type: number
  - name: LanguageSuffix # Optional. English is an empty string. Japanese = 'J'
    type: string
    default: ''
# The remaining parameters are Helper Parameters. Do not pass these in
  - name: JobName
    type: string
    default: ${{ format('Job_w{0}d_{1}_{2}{3}_{4}', parameters.OSVersion, parameters.LansaMajorVersion, parameters.LansaMinorVersion, parameters.LanguageSuffix, variables.VersionText) }}
  - name: VersionTextRoot
    type: string
    default: ${{ format('w{0}d-{1}-{2}{3}', parameters.OSVersion, parameters.LansaMajorVersion, parameters.LansaMinorVersion, parameters.LanguageSuffix) }}
  - name: InstallLanguagePack
    type: boolean
    default: ${{ if eq(parameters.LanguageSuffix, 'j') }} then $True else $False
  - name: InstallLanguagePack
    type: string
    default: ${{ if eq(parameters.LanguageSuffix, 'j') }} then 'JPN' else ''

jobs:
- job: ${{ parameters.JobName }}
  displayName: '${{ parameters.VersionTextRoot }}-$(VersionText)'
  timeoutInMinutes: ${{ parameters.ScriptTimeout }}
  condition: and(succeeded(), or(eq(variables['Build-w${{ parameters.VersionTextRoot }}'], 'true'), eq(variables['Build-all'], 'true')))
  variables:
    JobName: ${{ parameters.VersionTextRoot }}
    JobVersionText: '${{ parameters.VersionTextRoot }}-$(VersionText)'
    JobResourceGroupName: 'BakingDP-${{ parameters.VersionTextRoot }}-$(VersionText)'
    JobImageName: ${{ parameters.CloudImageName }}
    JobVersionMajor: ${{ parameters.LansaMajorVersion }}
    JobVersionMinor: ${{ parameters.LansaMinorVersion }}
    JobTag: 'test-temp'
    JobImageUrlOutputFileName: "${{ parameters.VersionTextRoot }}-$(VersionText).txt"
    JobTestVmName: T${{ parameters.OSVersion }}${{ parameters.LansaMajorVersion }}${{ parameters.LansaMinorVersion }}${{ parameters.LanguageString }}${{ variables['Build.BuildId'] }}

  pool:
    vmImage: $(vmImage)

  steps:
  - checkout: self
    fetchTags: false

  - task: PowerShell@2
    name: ''
    displayName: Install PS Module
    inputs:
      filePath: scripts/install-powershell-modules-azure.ps1
      errorActionPreference: continue

  - task: PowerShell@2
    name: ''
    displayName: Azure Login
    inputs:
      filePath: scripts/AzureLogin.ps1
      arguments: -CloudAccount $(azureUserId) -CloudSecret (ConvertTo-SecureString "$(clientSecret)" -AsPlainText -force)
      workingDirectory: scripts

  - task: PowerShell@2
    condition: true
    name: BuildImage
    displayName: Build Image
    timeoutInMinutes: ${{ parameters.ScriptTimeout }}
    inputs:
      filePath: scripts/bake-scalable-azure-image-pipeline.ps1
      arguments: -VersionText $(JobVersionText) -VersionMajor $(JobVersionMajor) -VersionMinor $(JobVersionMinor) -AmazonAMIName $(JobImageName) -GitBranch "$(GitBranch)" -Cloud 'Azure' -Win2012 $false -GitUserName $(GitUserName) -MaxRetry $(MaxRetry) -ExternalIPAddresses $(ExternalIPAddresses) -InstallLanguagePack:$(InstallLanguagePack) -Language $(Language)
      workingDirectory: scripts

  - task: PowerShell@2
    name: ''
    displayName: 'Tag RG'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Tagging $(JobResourceGroupName) with Usage = '$(JobTag)'" | Out-Default | Write-Host

        Set-AzResourceGroup -Name $(JobResourceGroupName) -Tag @{ Usage = '$(JobTag)' }

  - task: PowerShell@2
    name: ''
    displayName: 'Generate: Image URL'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Writing the Full Image URL $(BuildImage.ImageUrl) in the $(Build.ArtifactStagingDirectory)" | Out-Default | Write-Host

        Out-File -FilePath (Join-Path $(Build.ArtifactStagingDirectory) $(JobImageUrlOutputFileName)) -InputObject $(BuildImage.ImageUrl) | Out-Default | Write-Host

        Write-Host "Full Image URL written successfully" | Out-Default | Write-Host

  - task: PowerShell@2
    name: ''
    displayName: VM Tests
    env:
        TestImageName: $(JobVersionText)
        TestCloudName: Azure
        AtomicBuild: $(atomic-build)
        TestVmName: $(JobTestVmName)
    inputs:
      filePath: scripts/invoke-pester-tests.ps1
  - task: PublishTestResults@2
    displayName: Publish Test Results **/Test-*.xml
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/Test-*.xml'
      testRunTitle: $(VersionTextRoot)

  - task: PublishBuildArtifacts@1
    name: ''
    displayName: 'Publish Artifact: Image URL'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/$(VersionTextRoot).txt
      ArtifactName: $(VersionTextRoot)
      FileCopyOptions: ''

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Delete RG
    inputs:
      ConnectedServiceName: $(ConnectedServiceName)
      subscriptionName: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3
      action: DeleteRG
      resourceGroupName: $(JobResourceGroupName)