parameters:
  - name: ScriptTimeout # Can't refer to a (numeric?) variable in a template thats declared in the parent yml. Hence it must be passed as a parameter
    type: number

jobs:

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '22'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2022-IMAGE-NAME)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '22'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2022-IMAGE-NAME)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '16'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2016-IMAGE-NAME)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '16'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2016-IMAGE-NAME)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '19'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2019-IMAGE-NAME)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '19'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2019-IMAGE-NAME)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '16'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    LanguageSuffix: 'j'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2016-IMAGE-NAME-JPN)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '16'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    LanguageSuffix: 'j'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2016-IMAGE-NAME-JPN)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '19'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    LanguageSuffix: 'j'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2019-IMAGE-NAME-JPN)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '19'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    LanguageSuffix: 'j'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2019-IMAGE-NAME-JPN)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '22'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    LanguageSuffix: 'j'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2022-IMAGE-NAME-JPN)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}

- template: AzureBuildImage.yml
  parameters:
    OSVersion: '22'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    LanguageSuffix: 'j'
    VersionText: ${{ variables.VersionText }}
    CloudImageName: $(Windows-2022-IMAGE-NAME-JPN)
    ScriptTimeout: ${{ parameters.ScriptTimeout }}
