variables:
  - group: 'External IP Addresses'
  - group: 'Image Names'
  - group: 'Azure Logins'

  - name: azureUserId
    value: PowershellScriptsSP

  - name: vmImage
    value: Default

  - name:  TestCloudName
    value: 'Azure'

  - name: AtomicBuild
    value: $False

  - name: ScriptTimeout
    value: 360

  # When VersionText is incremented, the PublishedVersionText variable in the Group "SKU Versions" must also be updated to match the previous value of VersionText. This is because the PublishedVersionText variable is used to determine which image version to use for testing, and it should point to the last successfully published image version.
  - name: VersionText
    value: 23

jobs:

- template: AzureDevOps/templates/AzureBuildAllImages.yml
  parameters:
    VersionText: ${{ variables.VersionText }}
    ScriptTimeout: ${{ variables.ScriptTimeout }}

