variables:
  - group: 'External IP Addresses'
  - group: 'Image Names'
  - group: 'Azure Logins'

  - name: azureUserId
    value: PowershellScriptsSP

  - name: vmImage
    value: windows-2022

  - name:  TestCloudName
    value: 'Azure'

  - name: AtomicBuild
    value: $False

  - name: ScriptTimeout
    value: 360

parameters:
  - name: VersionText # Promote the Library Variable to a template parameter so that it may be used in a template expression at compile time
    type: string
    default: ''

jobs:

- template: AzureDevOps/templates/AzureBuildAllImages.yml
  parameters:
    VersionText: $(VersionText )
    ScriptTimeout: ${{ variables.ScriptTimeout }}

