variables:
  - group: 'External IP Addresses'
  - group: 'Image Names'
  - group: 'Azure Logins'
  - group: 'SKU Versions'

  - name: azureUserId
    value: PowershellScriptsSP

  - name: vmImage
    value: windows-2022

  - name:  TestCloudName
    value: 'Azure'

  - name: AtomicBuild
    value: $False

  - name: ScriptTimeout
    value: 360

  - name: VersionText        # redeclare here to make it settable at queue time
    value: $(VersionText)    # pulls default from the group

jobs:

- template: AzureDevOps/templates/AzureBuildAllImages.yml
  parameters:
    VersionText: ${{ variables.VersionText }}
    ScriptTimeout: ${{ variables.ScriptTimeout }}

