name: CI Images-$(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - debug/paas

pr: none

variables:
  - group: 'External IP Addresses'
  - group: 'Image Names'
  - group: 'Azure Logins'
  - name: atomic-build
    value: $False
  - name: azureUserId
    value: PowershellScriptsSP
  - name: VersionText
    value: 0
  - name: vmImage
    value: windows-2022
  - name:  TestCloudName
    value: 'Azure'
  - name: AtomicBuild
    value: $True
  - name: ScriptTimeout
    value: 360

jobs:

- template: AzureDevOps/templates/AzureBuildImage.yml
  parameters:
    OSVersion: '22'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    CloudImageName: $(Windows-2022-IMAGE-NAME)
    ScriptTimeout: ${{ variables.ScriptTimeout }}

- template: AzureDevOps/templates/AzureBuildImage.yml
  parameters:
    OSVersion: '22'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    CloudImageName: $(Windows-2022-IMAGE-NAME)
    ScriptTimeout: ${{ variables.ScriptTimeout }}

- template: AzureDevOps/templates/AzureBuildImage.yml
  parameters:
    OSVersion: '16'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    CloudImageName: $(Windows-2016-IMAGE-NAME)
    ScriptTimeout: ${{ variables.ScriptTimeout }}

- template: AzureDevOps/templates/AzureBuildImage.yml
  parameters:
    OSVersion: '16'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    CloudImageName: $(Windows-2016-IMAGE-NAME)
    ScriptTimeout: ${{ variables.ScriptTimeout }}

- template: AzureDevOps/templates/AzureBuildImage.yml
  parameters:
    OSVersion: '19'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    CloudImageName: $(Windows-2019-IMAGE-NAME)
    ScriptTimeout: ${{ variables.ScriptTimeout }}

- template: AzureDevOps/templates/AzureBuildImage.yml
  parameters:
    OSVersion: '19'
    LansaMajorVersion: '15'
    LansaMinorVersion: '0'
    CloudImageName: $(Windows-2019-IMAGE-NAME)
    ScriptTimeout: ${{ variables.ScriptTimeout }}

- template: AzureDevOps/templates/AzureBuildImage.yml
  parameters:
    OSVersion: '16'
    LansaMajorVersion: '16'
    LansaMinorVersion: '0'
    LanguageSuffix: 'j'
    CloudImageName: $(Windows-2019-IMAGE-NAME-JPN)
    ScriptTimeout: ${{ variables.ScriptTimeout }}

- job: Job_8
  displayName: 'Agent job : w16d-15-0j'
  timeoutInMinutes: 360
  condition: and(succeeded(), or(eq(variables['Build-w16d-15-0j'], 'true'), eq(variables['Build-all'], 'true')))
  pool:
    vmImage: $(vmImage)
  steps:
  - checkout: self
    fetchTags: false
  - task: PowerShell@2
    displayName: Install PS Module
    inputs:
      filePath: scripts/install-powershell-modules-azure.ps1
      errorActionPreference: continue

  - task: PowerShell@2
    displayName: Azure Login
    inputs:
      filePath: scripts/AzureLogin.ps1
      arguments: -CloudAccount $(azureUserId) -CloudSecret (ConvertTo-SecureString "$(clientSecret)" -AsPlainText -force)
      workingDirectory: scripts

  - task: PowerShell@2
    name: BuildImage
    displayName: Build Image
    timeoutInMinutes: 120
    inputs:
      filePath: scripts/bake-scalable-azure-image-pipeline.ps1
      arguments: -VersionText 'w16d-15-0j-$(VersionText-w16d-15-0j)' -VersionMajor 15 -VersionMinor 0 -AmazonAMIName $(Windows-2016-IMAGE-URI-JPN) -GitBranch "$(GitBranch)" -Cloud 'Azure' -Win2012 $false -GitUserName $(GitUserName) -MaxRetry $(MaxRetry) -ExternalIPAddresses $(ExternalIPAddresses) -InstallLanguagePack:$true -Language 'JPN'
      workingDirectory: scripts

  - task: PowerShell@2
    name: ''
    displayName: 'Azure Resource Group Tagging'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Tagging BakingDP-w16d-15-0j-$(VersionText-w16d-15-0j) with Usage = "test-temp"" | Out-Default | Write-Host

        Set-AzResourceGroup -Name "BakingDP-w16d-15-0j-$(VersionText-w16d-15-0j)" -Tag @{ Usage = "test-temp" }

  - task: PowerShell@2
    displayName: 'Generate: Image URL'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Writing the Full Image URL $(BuildImage.ImageUrl) in the $(Build.ArtifactStagingDirectory)" | Out-Default | Write-Host

        Out-File -FilePath (Join-Path $(Build.ArtifactStagingDirectory) "w16d-15-0j.txt") -InputObject $(BuildImage.ImageUrl) | Out-Default | Write-Host

        Write-Host "Full Image URL written successfully" | Out-Default | Write-Host

  - task: PowerShell@2
    displayName: VM Tests
    env:
        TestImageName: w16d-15-0j-$(VersionText-w16d-15-0j)
        TestCloudName: Azure
        AtomicBuild: $(atomic-build)
        TestVmName: Test16150j$(VersionText-w16d-15-0j)
    inputs:
      filePath: scripts/invoke-pester-tests.ps1

  - task: PublishTestResults@2
    displayName: Publish Test Results **/Test-*.xml
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/Test-*.xml'
      testRunTitle: w16d-15-0j

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Image URL'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/w16d-15-0j.txt
      ArtifactName: w16d-15-0j
      FileCopyOptions: ''

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Delete Resource Group
    inputs:
      ConnectedServiceName: $(ConnectedServiceName)
      subscriptionName: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3
      action: DeleteRG
      resourceGroupName: BakingDP-w16d-15-0j-$(VersionText-w16d-15-0j)
- job: Job_9
  displayName: 'Agent job : w19d-15-0j'
  timeoutInMinutes: 360
  condition: and(succeeded(), or(eq(variables['Build-w19d-15-0j'], 'true'), eq(variables['Build-all'], 'true')))
  pool:
    vmImage: $(vmImage)
  steps:
  - checkout: self
    fetchTags: false
  - task: PowerShell@2
    displayName: Install PS Module
    inputs:
      filePath: scripts/install-powershell-modules-azure.ps1
      errorActionPreference: continue

  - task: PowerShell@2
    displayName: Azure Login
    inputs:
      filePath: scripts/AzureLogin.ps1
      arguments: -CloudAccount $(azureUserId) -CloudSecret (ConvertTo-SecureString "$(clientSecret)" -AsPlainText -force)
      workingDirectory: scripts

  - task: PowerShell@2
    name: BuildImage
    displayName: Build Image
    timeoutInMinutes: 120
    inputs:
      filePath: scripts/bake-scalable-azure-image-pipeline.ps1
      arguments: -VersionText 'w19d-15-0j-$(VersionText-w19d-15-0j)' -VersionMajor 15 -VersionMinor 0 -AmazonAMIName $(Windows-2019-IMAGE-URI-JPN) -GitBranch "$(GitBranch)" -Cloud 'Azure' -Win2012 $false -GitUserName $(GitUserName) -MaxRetry $(MaxRetry) -ExternalIPAddresses $(ExternalIPAddresses) -InstallLanguagePack:$true -Language 'JPN'
      workingDirectory: scripts

  - task: PowerShell@2
    name: ''
    displayName: 'Azure Resource Group Tagging'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Tagging BakingDP-w19d-15-0j-$(VersionText-w19d-15-0j) with Usage = "test-temp"" | Out-Default | Write-Host

        Set-AzResourceGroup -Name "BakingDP-w19d-15-0j-$(VersionText-w19d-15-0j)" -Tag @{ Usage = "test-temp" }

  - task: PowerShell@2
    displayName: 'Generate: Image URL'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Writing the Full Image URL $(BuildImage.ImageUrl) in the $(Build.ArtifactStagingDirectory)" | Out-Default | Write-Host

        Out-File -FilePath (Join-Path $(Build.ArtifactStagingDirectory) "w19d-15-0j.txt") -InputObject $(BuildImage.ImageUrl) | Out-Default | Write-Host

        Write-Host "Full Image URL written successfully" | Out-Default | Write-Host

  - task: PowerShell@2
    displayName: VM Tests
    env:
        TestImageName: w19d-15-0j-$(VersionText-w19d-15-0j)
        TestCloudName: Azure
        AtomicBuild: $(atomic-build)
        TestVmName: Test19150j$(VersionText-w19d-15-0j)
    inputs:
      filePath: scripts/invoke-pester-tests.ps1

  - task: PublishTestResults@2
    displayName: Publish Test Results **/Test-*.xml
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/Test-*.xml'
      testRunTitle: w19d-15-0j

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Image URL'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/w19d-15-0j.txt
      ArtifactName: w19d-15-0j
      FileCopyOptions: ''

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Delete Resource Group
    inputs:
      ConnectedServiceName: $(ConnectedServiceName)
      subscriptionName: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3
      action: DeleteRG
      resourceGroupName: BakingDP-w19d-15-0j-$(VersionText-w19d-15-0j)

- job: Job_10
  displayName: 'Agent job : w19d-16-0j'
  timeoutInMinutes: 360
  condition: and(succeeded(), or(eq(variables['Build-w19d-16-0j'], 'true'), eq(variables['Build-all'], 'true')))
  pool:
    vmImage: $(vmImage)
  steps:
  - checkout: self
    fetchTags: false
  - task: PowerShell@2
    displayName: Install PS Module
    inputs:
      filePath: scripts/install-powershell-modules-azure.ps1
      errorActionPreference: continue

  - task: PowerShell@2
    displayName: Azure Login
    inputs:
      filePath: scripts/AzureLogin.ps1
      arguments: -CloudAccount $(azureUserId) -CloudSecret (ConvertTo-SecureString "$(clientSecret)" -AsPlainText -force)
      workingDirectory: scripts

  - task: PowerShell@2
    name: BuildImage
    displayName: Build Image
    timeoutInMinutes: 120
    inputs:
      filePath: scripts/bake-scalable-azure-image-pipeline.ps1
      arguments: -VersionText 'w19d-16-0j-$(VersionText-w19d-16-0j)' -VersionMajor 16 -VersionMinor 0 -AmazonAMIName $(Windows-2019-IMAGE-URI-JPN) -GitBranch "$(GitBranch)" -Cloud 'Azure' -Win2012 $false -GitUserName $(GitUserName) -MaxRetry $(MaxRetry) -ExternalIPAddresses $(ExternalIPAddresses) -InstallLanguagePack:$true -Language 'JPN'
      workingDirectory: scripts

  - task: PowerShell@2
    name: ''
    displayName: 'Azure Resource Group Tagging'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Tagging BakingDP-w19d-16-0j-$(VersionText-w19d-16-0j) with Usage = "test-temp"" | Out-Default | Write-Host

        Set-AzResourceGroup -Name "BakingDP-w19d-16-0j-$(VersionText-w19d-16-0j)" -Tag @{ Usage = "test-temp" }

  - task: PowerShell@2
    displayName: 'Generate: Image URL'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Writing the Full Image URL $(BuildImage.ImageUrl) in the $(Build.ArtifactStagingDirectory)" | Out-Default | Write-Host

        Out-File -FilePath (Join-Path $(Build.ArtifactStagingDirectory) "w19d-16-0j.txt") -InputObject $(BuildImage.ImageUrl) | Out-Default | Write-Host

        Write-Host "Full Image URL written successfully" | Out-Default | Write-Host

  - task: PowerShell@2
    displayName: VM Tests
    env:
        TestImageName: w19d-16-0j-$(VersionText-w19d-16-0j)
        TestCloudName: Azure
        AtomicBuild: $(atomic-build)
        TestVmName: Test19160j$(VersionText-w19d-16-0j)
    inputs:
      filePath: scripts/invoke-pester-tests.ps1

  - task: PublishTestResults@2
    displayName: Publish Test Results **/Test-*.xml
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/Test-*.xml'
      testRunTitle: w19d-16-0j

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Image URL'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/w19d-16-0j.txt
      ArtifactName: w19d-16-0j
      FileCopyOptions: ''

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Delete Resource Group
    inputs:
      ConnectedServiceName: $(ConnectedServiceName)
      subscriptionName: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3
      action: DeleteRG
      resourceGroupName: BakingDP-w19d-16-0j-$(VersionText-w19d-16-0j)

- job: Job_11
  displayName: 'Agent job : w22d-15-0j'
  timeoutInMinutes: 360
  condition: and(succeeded(), or(eq(variables['Build-w22d-15-0j'], 'true'), eq(variables['Build-all'], 'true')))
  pool:
    vmImage: $(vmImage)
  steps:
  - checkout: self
    fetchTags: false
  - task: PowerShell@2
    displayName: Install PS Module
    inputs:
      filePath: scripts/install-powershell-modules-azure.ps1
      errorActionPreference: continue

  - task: PowerShell@2
    displayName: Azure Login
    inputs:
      filePath: scripts/AzureLogin.ps1
      arguments: -CloudAccount $(azureUserId) -CloudSecret (ConvertTo-SecureString "$(clientSecret)" -AsPlainText -force)
      workingDirectory: scripts

  - task: PowerShell@2
    name: BuildImage
    displayName: Build Image
    timeoutInMinutes: 120
    inputs:
      filePath: scripts/bake-scalable-azure-image-pipeline.ps1
      arguments: -VersionText 'w22d-15-0j-$(VersionText-w22d-15-0j)' -VersionMajor 15 -VersionMinor 0 -AmazonAMIName $(Windows-2022-IMAGE-URI-JPN) -GitBranch "$(GitBranch)" -Cloud 'Azure' -Win2012 $false -GitUserName $(GitUserName) -MaxRetry $(MaxRetry) -ExternalIPAddresses $(ExternalIPAddresses) -InstallLanguagePack:$true -Language 'JPN'
      workingDirectory: scripts

  - task: PowerShell@2
    name: ''
    displayName: 'Azure Resource Group Tagging'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Tagging BakingDP-w22d-15-0j-$(VersionText-w22d-15-0j) with Usage = "test-temp"" | Out-Default | Write-Host

        Set-AzResourceGroup -Name "BakingDP-w22d-15-0j-$(VersionText-w22d-15-0j)" -Tag @{ Usage = "test-temp" }

  - task: PowerShell@2
    displayName: 'Generate: Image URL'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Writing the Full Image URL $(BuildImage.ImageUrl) in the $(Build.ArtifactStagingDirectory)" | Out-Default | Write-Host

        Out-File -FilePath (Join-Path $(Build.ArtifactStagingDirectory) "w22d-15-0j.txt") -InputObject $(BuildImage.ImageUrl) | Out-Default | Write-Host

        Write-Host "Full Image URL written successfully" | Out-Default | Write-Host

  - task: PowerShell@2
    displayName: VM Tests
    env:
        TestImageName: w22d-15-0j-$(VersionText-w22d-15-0j)
        TestCloudName: Azure
        AtomicBuild: $(atomic-build)
        TestVmName: Test22150j$(VersionText-w22d-15-0j)
    inputs:
      filePath: scripts/invoke-pester-tests.ps1

  - task: PublishTestResults@2
    displayName: Publish Test Results **/Test-*.xml
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/Test-*.xml'
      testRunTitle: w22d-15-0j

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Image URL'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/w22d-15-0j.txt
      ArtifactName: w22d-15-0j
      FileCopyOptions: ''

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Delete Resource Group
    inputs:
      ConnectedServiceName: $(ConnectedServiceName)
      subscriptionName: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3
      action: DeleteRG
      resourceGroupName: BakingDP-w22d-15-0j-$(VersionText-w22d-15-0j)

- job: Job_12
  displayName: 'Agent job : w22d-16-0j'
  timeoutInMinutes: 360
  condition: and(succeeded(), or(eq(variables['Build-w22d-16-0j'], 'true'), eq(variables['Build-all'], 'true')))
  pool:
    vmImage: $(vmImage)
  steps:
  - checkout: self
    fetchTags: false
  - task: PowerShell@2
    displayName: Install PS Module
    inputs:
      filePath: scripts/install-powershell-modules-azure.ps1
      errorActionPreference: continue

  - task: PowerShell@2
    displayName: Azure Login
    inputs:
      filePath: scripts/AzureLogin.ps1
      arguments: -CloudAccount $(azureUserId) -CloudSecret (ConvertTo-SecureString "$(clientSecret)" -AsPlainText -force)
      workingDirectory: scripts

  - task: PowerShell@2
    name: BuildImage
    displayName: Build Image
    timeoutInMinutes: 120
    inputs:
      filePath: scripts/bake-scalable-azure-image-pipeline.ps1
      arguments: -VersionText 'w22d-16-0j-$(VersionText-w22d-16-0j)' -VersionMajor 16 -VersionMinor 0 -AmazonAMIName $(Windows-2022-IMAGE-URI-JPN) -GitBranch "$(GitBranch)" -Cloud 'Azure' -Win2012 $false -GitUserName $(GitUserName) -MaxRetry $(MaxRetry) -ExternalIPAddresses $(ExternalIPAddresses) -InstallLanguagePack:$true -Language 'JPN'
      workingDirectory: scripts

  - task: PowerShell@2
    name: ''
    displayName: 'Azure Resource Group Tagging'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Tagging BakingDP-w22d-16-0j-$(VersionText-w22d-16-0j) with Usage = "test-temp"" | Out-Default | Write-Host

        Set-AzResourceGroup -Name "BakingDP-w22d-16-0j-$(VersionText-w22d-16-0j)" -Tag @{ Usage = "test-temp" }

  - task: PowerShell@2
    displayName: 'Generate: Image URL'
    inputs:
      targetType: inline
      script: >-
        Write-Host "Writing the Full Image URL $(BuildImage.ImageUrl) in the $(Build.ArtifactStagingDirectory)" | Out-Default | Write-Host

        Out-File -FilePath (Join-Path $(Build.ArtifactStagingDirectory) "w22d-16-0j.txt") -InputObject $(BuildImage.ImageUrl) | Out-Default | Write-Host

        Write-Host "Full Image URL written successfully" | Out-Default | Write-Host

  - task: PowerShell@2
    displayName: VM Tests
    env:
        TestImageName: w22d-16-0j-$(VersionText-w22d-16-0j)
        TestCloudName: Azure
        AtomicBuild: $(atomic-build)
        TestVmName: Test22160j$(VersionText-w22d-16-0j)
    inputs:
      filePath: scripts/invoke-pester-tests.ps1

  - task: PublishTestResults@2
    displayName: Publish Test Results **/Test-*.xml
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/Test-*.xml'
      testRunTitle: w22d-16-0j

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Image URL'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/w22d-16-0j.txt
      ArtifactName: w22d-16-0j
      FileCopyOptions: ''

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Delete Resource Group
    inputs:
      ConnectedServiceName: $(ConnectedServiceName)
      subscriptionName: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3
      action: DeleteRG
      resourceGroupName: BakingDP-w22d-16-0j-$(VersionText-w22d-16-0j)
...
